server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service1
          uri: http://localhost:8081
          predicates:
            - Path=/service1/**

        - id: service2
          uri: http://localhost:8082
          predicates:
            - Path=/service2/**

eureka:
  client:
    register-with-eureka: false